import { describe, expect, it } from 'vitest'
import * as Logix from '../../src/index.js'
import { readFileSync } from 'node:fs'

describe('core root exports boundary', () => {
  it('does not expose any standalone legacy field family', () => {
    const retiredFieldSurface = ['State', 'Tr', 'ait'].join('')
    const retiredLifecycleSurface = ['Tr', 'ait', 'Lifecycle'].join('')
    const pkg = JSON.parse(readFileSync(new URL('../../package.json', import.meta.url), 'utf8')) as {
      readonly exports?: Record<string, unknown>
      readonly publishConfig?: { readonly exports?: Record<string, unknown> }
    }

    expect(Object.keys(Logix).sort()).not.toContain('Action')
    expect(retiredFieldSurface in Logix).toBe(false)
    expect(retiredLifecycleSurface in Logix).toBe(false)
    expect('FieldKernel' in Logix).toBe(false)
    expect('MatchBuilder' in Logix).toBe(false)
    expect('ScopeRegistry' in Logix).toBe(false)
    expect('Root' in Logix).toBe(false)
    expect('Env' in Logix).toBe(false)
    expect('Platform' in Logix).toBe(false)
    expect('Middleware' in Logix).toBe(false)
    expect('InternalContracts' in Logix).toBe(false)
    expect('EffectOp' in Logix).toBe(false)
    expect('Workflow' in Logix).toBe(false)
    expect('Process' in Logix).toBe(false)
    expect('Flow' in Logix).toBe(false)
    expect('Link' in Logix).toBe(false)
    expect('Debug' in Logix).toBe(false)
    expect('Observability' in Logix).toBe(false)
    expect('Reflection' in Logix).toBe(false)
    expect('Kernel' in Logix).toBe(false)
    expect('ReadQuery' in Logix).toBe(false)
    expect('ExternalStore' in Logix).toBe(false)
    expect(pkg.exports?.['./repo-internal/*']).toBeUndefined()
    expect(pkg.exports?.['./repo-internal/InternalContracts']).toBeDefined()
    expect(pkg.exports?.['./repo-internal/debug-api']).toBeDefined()
    expect(pkg.exports?.['./repo-internal/evidence-api']).toBeDefined()
    expect(pkg.exports?.['./repo-internal/reflection-api']).toBeDefined()
    expect(pkg.exports?.['./repo-internal/kernel-api']).toBeDefined()
    expect(pkg.exports?.['./repo-internal/effect-op']).toBeDefined()
    expect(pkg.exports?.['./MatchBuilder']).toBeUndefined()
    expect(pkg.exports?.['./Root']).toBeUndefined()
    expect(pkg.exports?.['./Env']).toBeUndefined()
    expect(pkg.exports?.['./Platform']).toBeUndefined()
    expect(pkg.exports?.['./Middleware']).toBeUndefined()
    expect(pkg.exports?.['./EffectOp']).toBeUndefined()
    expect(pkg.exports?.['./Actions']).toBeUndefined()
    expect(pkg.exports?.['./Bound']).toBeUndefined()
    expect(pkg.exports?.['./Handle']).toBeUndefined()
    expect(pkg.exports?.['./Logic']).toBeUndefined()
    expect(pkg.exports?.['./ModuleTag']).toBeUndefined()
    expect(pkg.exports?.['./ReadQuery']).toBeUndefined()
    expect(pkg.exports?.['./ExternalStore']).toBeUndefined()
    expect(pkg.exports?.['./Resource']).toBeUndefined()
    expect(pkg.exports?.['./State']).toBeUndefined()
    expect(pkg.publishConfig?.exports?.['./MatchBuilder']).toBeUndefined()
    expect(pkg.publishConfig?.exports?.['./Root']).toBeUndefined()
    expect(pkg.publishConfig?.exports?.['./Env']).toBeUndefined()
    expect(pkg.publishConfig?.exports?.['./Platform']).toBeUndefined()
    expect(pkg.publishConfig?.exports?.['./Middleware']).toBeUndefined()
    expect(pkg.publishConfig?.exports?.['./EffectOp']).toBeUndefined()
    expect(pkg.publishConfig?.exports?.['./Actions']).toBeUndefined()
    expect(pkg.publishConfig?.exports?.['./Bound']).toBeUndefined()
    expect(pkg.publishConfig?.exports?.['./Handle']).toBeUndefined()
    expect(pkg.publishConfig?.exports?.['./Logic']).toBeUndefined()
    expect(pkg.publishConfig?.exports?.['./ModuleTag']).toBeUndefined()
    expect(pkg.publishConfig?.exports?.['./repo-internal/*']).toBeUndefined()
    expect(pkg.publishConfig?.exports?.['./repo-internal/InternalContracts']).toBeNull()
    expect(pkg.publishConfig?.exports?.['./repo-internal/debug-api']).toBeNull()
    expect(pkg.publishConfig?.exports?.['./repo-internal/evidence-api']).toBeNull()
    expect(pkg.publishConfig?.exports?.['./repo-internal/reflection-api']).toBeNull()
    expect(pkg.publishConfig?.exports?.['./repo-internal/kernel-api']).toBeNull()
    expect(pkg.publishConfig?.exports?.['./repo-internal/effect-op']).toBeNull()
    expect(pkg.publishConfig?.exports?.['./ReadQuery']).toBeUndefined()
    expect(pkg.publishConfig?.exports?.['./ExternalStore']).toBeUndefined()
    expect(pkg.publishConfig?.exports?.['./Resource']).toBeUndefined()
    expect(pkg.publishConfig?.exports?.['./State']).toBeUndefined()
  })
})
